/*
 * Copyright 2024 The OpenSSL Project Authors. All Rights Reserved.
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 *
 * !!!    D O   N O T   E D I T    !!!
 * This file is generated by genkeys-setpeer.sh script.
 */

#define PEM_DH	\
    "-----BEGIN PRIVATE KEY-----\n"\
    "MIIBPwIBADCCARcGCSqGSIb3DQEDATCCAQgCggEBAP//////////rfhUWKK7Spqv\n"\
    "3FYgJz088di5xYPOLTaVqeE2QRRkM/vMk53OJJs++X0v42NjDHXY9oGyAq7EYXrT\n"\
    "3x7V1f1lYSQz9R9fBm7QhWNlVT3tGvO1VxNef1fJNZhPDHDg5ot34qaJ2vPv6HId\n"\
    "8VihNq3nNTCsyk9IOnl6vAqxgrMk+2HRCKlLssjj+7lq2rdg1/RoHU9Co945TfSu\n"\
    "Vu3nY3K7GQsHp8juCm1wngL84c334uzANATNKDQvYZFy/pzphYP/jk8SMu7ygYPD\n"\
    "/jsbTG+tczu1/LwuwiAFxY7xg30Wg7LG80omwbLv+ohrQjhhKFyX//////////8C\n"\
    "AQIEHwIdAUPA2c1HwFn7wC9qTm/nSHQrVCjp23k/mZ7EQJs=\n"\
    "-----END PRIVATE KEY-----\n"

#define PEM_EC256	\
    "-----BEGIN PRIVATE KEY-----\n"\
    "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgo7+2q+TSuuBpMp5V\n"\
    "xiy2jRhOSR7SAm0XTI2+cyOmorahRANCAAQMlJ7LOVBjZL04Al8S7oBHuAz8iaI5\n"\
    "vMze2gk79FxD+SFXXzAaD/GJ2aifdLlhs2By0MXMLTU4i41rdi9wPVZ+\n"\
    "-----END PRIVATE KEY-----\n"

#define PEM_EC521	\
    "-----BEGIN PRIVATE KEY-----\n"\
    "MIHuAgEAMBAGByqGSM49AgEGBSuBBAAjBIHWMIHTAgEBBEIBTUijKdOUIabTysEB\n"\
    "LP9Fr4uIJiR2wqDGaIDrMsZfon8vMtewwgsb+obF8hmR9jQHki65Wkqbhb0DvOku\n"\
    "T7ZC3P6hgYkDgYYABAGLNLRg8Us3dIHTTT01O3kVZvwB2J8GBSYwXGO0/OuLftXF\n"\
    "w0lp+EMzbuBYBrKXAtubvoF9qsQWDgbNzzesqoEf1wGnl6B8wnQCm2TvsGytDIig\n"\
    "dPTP0iFK3AHEu3lwAs1jFQ5GWV+txNfwKjpeXmqFYKzyjPVCTx6rP7xzI4orLRU+\n"\
    "ow==\n"\
    "-----END PRIVATE KEY-----\n"

#define PEM_X25519	\
    "-----BEGIN PRIVATE KEY-----\n"\
    "MC4CAQAwBQYDK2VuBCIEINCKRBdqruU8C8/+y0fzvorK8dcrV1c6MiMqObLxjudR\n"\
    "-----END PRIVATE KEY-----\n"

static const char *sample_keys[] = {
    PEM_DH,
    PEM_EC256,
    PEM_EC521,
    PEM_X25519,
    NULL
};

static const size_t sample_key_sizes[] = {
    sizeof(PEM_DH) - 1,
    sizeof(PEM_EC256) - 1,
    sizeof(PEM_EC521) - 1,
    sizeof(PEM_X25519) - 1,
};

enum {
    SAMPLE_DH,
    SAMPLE_EC256,
    SAMPLE_EC521,
    SAMPLE_X25519,
    SAMPLE_ALL,
    SAMPLE_INVALID
};

static const char *sample_names[] = {
    "dh",
    "ec256",
    "ec521",
    "x25519",
    "all",
    NULL
};
